
-- 1
-- SELECT MIN(AV_MARK)
-- FROM STUDENTS_MARKS

-- 2
-- SELECT MAX(AV_MARK)
-- FROM STUDENTS_MARKS

-- 3
-- SELECT CITY, COUNT(*) AS NUMBEROFSTUDENTS
-- FROM STUDENTS_MARKS
-- GROUP BY CITY;


-- 4
-- SELECT COUNTRY, COUNT(*) AS NUMBEROFSTUDENTS
-- FROM STUDENTS_MARKS
-- GROUP BY COUNTRY;


-- -- 5
-- SELECT COUNT(*) AS MIN_AV_NUM
-- FROM STUDENTS_MARKS
-- WHERE AV_MARK = (
--     SELECT MIN(AV_MARK) 
--     FROM STUDENTS_MARKS
-- );


-- 6
-- SELECT COUNT(*) AS MAX_AV_NUM
-- FROM STUDENTS_MARKS
-- WHERE AV_MARK = (
--     SELECT MAX(AV_MARK) 
--     FROM STUDENTS_MARKS
-- );


-- 7
-- SELECT GROUPNAME, COUNT(*) AS NUMBEROFSTUDENTS
-- FROM STUDENTS_MARKS
-- GROUP BY GROUPNAME


-- 8
-- SELECT GROUPNAME, AVG(AV_MARK) AS AVARAGEGRADE
-- FROM STUDENTS_MARKS
-- GROUP BY GROUPNAME;
